make Collections implement Iterator and Countable
php-slang/php-slang pull request #47
Opened 2018-05-08 22:04 UTC by IonBazan

This should Fix #42.
Tests are strongly inspired by https://github.com/doctrine/collections/blob/33407e41a31e448426563e33a6edf688461a9a86/tests/Doctrine/Tests/Common/Collections/BaseArrayCollectionTest.php

2018-05-08 22:06 UTC, IonBazan commented on src/PhpSlang/Collection/Generic/Component/IterableCollection.php
> +        reset($this->content);
I'm not quite sure if it's a good solution. Maybe we should create a new instance to make it immutable...

2018-05-09 08:28 UTC, Kryniol requested changes

2018-05-09 08:28 UTC, Kryniol commented on src/PhpSlang/Collection/Generic/Collection.php
> +interface Collection extends Iterator, Countable
where is the `Countable::count()` method implemented?

2018-05-09 08:28 UTC, Kryniol commented on src/PhpSlang/Collection/Generic/Collection.php
> +interface Collection extends Iterator, Countable
btw this is a compatibility break, I guess the PR should have the target branch set to some 2.0-dev created from master

2025-11-27 08:40 UTC, closed without merging